spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: ${PG_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:postgres}
